import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.time.format.TextStyle;
import java.util.Locale;
import javax.swing.JOptionPane;

public class AplikasiPerhitunganHari extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiPerhitunganHari
     */
    public AplikasiPerhitunganHari() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        lblBulan = new javax.swing.JLabel();
        cmbBulan = new javax.swing.JComboBox<>();
        lblTahun = new javax.swing.JLabel();
        spnTahun = new javax.swing.JSpinner();
        btnHitungHari = new javax.swing.JButton();
        lblHasil = new javax.swing.JLabel();
        lblJumlahHari = new javax.swing.JLabel();
        lblHariPertama = new javax.swing.JLabel();
        lblHariTerakhir = new javax.swing.JLabel();
        lblTanggal1 = new javax.swing.JLabel();
        calendarTanggal2 = new com.toedter.calendar.JCalendar();
        lblTanggal2 = new javax.swing.JLabel();
        calendarTanggal1 = new com.toedter.calendar.JCalendar();
        btnHitungSelisih = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        lblJudul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblJudul.setText("APLIKASI PERHITUNGAN HARI");

        lblBulan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBulan.setText("Pilih Bulan : ");

        cmbBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember", " " }));

        lblTahun.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTahun.setText("Masukkan Tahun :");

        btnHitungHari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHitungHari.setText("Hitung Hari");
        btnHitungHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungHariActionPerformed(evt);
            }
        });

        lblHasil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHasil.setText("Hasil : ");

        lblJumlahHari.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblJumlahHari.setText("Jumlah Hari :");

        lblHariPertama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHariPertama.setText("Hari Pertama :");

        lblHariTerakhir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHariTerakhir.setText("Hari Terakhir :");

        lblTanggal1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTanggal1.setText("Pilih Tanggal 1");

        lblTanggal2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTanggal2.setText("Pilih Tanggal 2");

        btnHitungSelisih.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHitungSelisih.setText("Hitung Selisih Hari");
        btnHitungSelisih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungSelisihActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTahun)
                                    .addComponent(lblBulan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblJudul)
                                    .addComponent(spnTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblHasil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHariTerakhir)
                                    .addComponent(lblHariPertama)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblJumlahHari)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTanggal1)
                                    .addComponent(calendarTanggal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTanggal2)
                                    .addComponent(calendarTanggal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(btnHitungSelisih))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(btnHitungHari)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblJudul)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBulan)
                    .addComponent(cmbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTahun)
                    .addComponent(spnTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnHitungHari)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHasil)
                    .addComponent(lblJumlahHari))
                .addGap(18, 18, 18)
                .addComponent(lblHariPertama)
                .addGap(18, 18, 18)
                .addComponent(lblHariTerakhir)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTanggal1)
                    .addComponent(lblTanggal2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calendarTanggal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calendarTanggal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnHitungSelisih)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungHariActionPerformed
        int bulan = cmbBulan.getSelectedIndex() + 1; // Januari = 0, jadi tambah 1
    int tahun = (int) spnTahun.getValue();
    
    // Buat tanggal awal bulan tersebut
    LocalDate tanggalAwal = LocalDate.of(tahun, bulan, 1);
    
    // Hitung jumlah hari dalam bulan itu
    int jumlahHari = tanggalAwal.lengthOfMonth();
    
    // Dapatkan hari pertama dan hari terakhir
    String hariPertama = tanggalAwal.getDayOfWeek()
            .getDisplayName(TextStyle.FULL, new Locale("id", "ID"));
    String hariTerakhir = tanggalAwal.withDayOfMonth(jumlahHari)
            .getDayOfWeek().getDisplayName(TextStyle.FULL, new Locale("id", "ID"));
    
    // Tampilkan hasil ke label
    lblJumlahHari.setText("Jumlah Hari : " + jumlahHari + " hari");
    lblHariPertama.setText("Hari Pertama : " + hariPertama);
    lblHariTerakhir.setText("Hari Terakhir : " + hariTerakhir);
    }//GEN-LAST:event_btnHitungHariActionPerformed

    private void btnHitungSelisihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungSelisihActionPerformed
           // Ambil tanggal dari kedua kalender
    java.util.Date tgl1 = calendarTanggal1.getDate();
    java.util.Date tgl2 = calendarTanggal2.getDate();

    // Konversi ke LocalDate
    LocalDate tanggal1 = new java.sql.Date(tgl1.getTime()).toLocalDate();
    LocalDate tanggal2 = new java.sql.Date(tgl2.getTime()).toLocalDate();

    // Hitung selisih
    long selisih = ChronoUnit.DAYS.between(tanggal1, tanggal2);

    // Tampilkan hasil dalam popup
    JOptionPane.showMessageDialog(this,
        "Selisih antara dua tanggal adalah " + Math.abs(selisih) + " hari.",
        "Hasil Perhitungan",
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnHitungSelisihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPerhitunganHari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitungHari;
    private javax.swing.JButton btnHitungSelisih;
    private com.toedter.calendar.JCalendar calendarTanggal1;
    private com.toedter.calendar.JCalendar calendarTanggal2;
    private javax.swing.JComboBox<String> cmbBulan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBulan;
    private javax.swing.JLabel lblHariPertama;
    private javax.swing.JLabel lblHariTerakhir;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJumlahHari;
    private javax.swing.JLabel lblTahun;
    private javax.swing.JLabel lblTanggal1;
    private javax.swing.JLabel lblTanggal2;
    private javax.swing.JSpinner spnTahun;
    // End of variables declaration//GEN-END:variables
}
